// <auto-generated />
using System;
using Hospital.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Hospital.Business.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Hospital.Business.Models.Medical.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MedicalRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrescribingDoctorId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.HasIndex("PrescribingDoctorId");

                    b.ToTable("Appointments");

                    b.HasDiscriminator().HasValue("Appointment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Hospital.Business.Models.Medical.MedicalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HospitalizationDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("Hospital.Business.Models.People.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DoctorId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Hospital.Business.Models.People.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Hospital.Business.Models.Medical.DiagnosticAppointment", b =>
                {
                    b.HasBaseType("Hospital.Business.Models.Medical.Appointment");

                    b.Property<string>("ProcedureName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Results")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("DiagnosticAppointment");
                });

            modelBuilder.Entity("Hospital.Business.Models.Medical.MedicationAppointment", b =>
                {
                    b.HasBaseType("Hospital.Business.Models.Medical.Appointment");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("MedicationAppointment");
                });

            modelBuilder.Entity("Hospital.Business.Models.Medical.ProphylacticAppointment", b =>
                {
                    b.HasBaseType("Hospital.Business.Models.Medical.Appointment");

                    b.Property<string>("ProcedureName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Appointments", t =>
                        {
                            t.Property("ProcedureName")
                                .HasColumnName("ProphylacticAppointment_ProcedureName");
                        });

                    b.HasDiscriminator().HasValue("ProphylacticAppointment");
                });

            modelBuilder.Entity("Hospital.Business.Models.People.Administrator", b =>
                {
                    b.HasBaseType("Hospital.Business.Models.People.User");

                    b.HasDiscriminator().HasValue("Administrator");
                });

            modelBuilder.Entity("Hospital.Business.Models.People.Doctor", b =>
                {
                    b.HasBaseType("Hospital.Business.Models.People.User");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Users", t =>
                        {
                            t.Property("DepartmentId")
                                .HasColumnName("Doctor_DepartmentId");
                        });

                    b.HasDiscriminator().HasValue("Doctor");
                });

            modelBuilder.Entity("Hospital.Business.Models.People.Nurse", b =>
                {
                    b.HasBaseType("Hospital.Business.Models.People.User");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("TEXT");

                    b.HasIndex("DepartmentId");

                    b.HasDiscriminator().HasValue("Nurse");
                });

            modelBuilder.Entity("Hospital.Business.Models.Medical.InjectionAppointment", b =>
                {
                    b.HasBaseType("Hospital.Business.Models.Medical.MedicationAppointment");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("InjectionAppointment");
                });

            modelBuilder.Entity("Hospital.Business.Models.Medical.PillAppointment", b =>
                {
                    b.HasBaseType("Hospital.Business.Models.Medical.MedicationAppointment");

                    b.Property<int>("Days")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("PillAppointment");
                });

            modelBuilder.Entity("Hospital.Business.Models.Medical.Appointment", b =>
                {
                    b.HasOne("Hospital.Business.Models.Medical.MedicalRecord", "MedicalRecord")
                        .WithMany("Appointments")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Business.Models.People.Doctor", "PrescribingDoctor")
                        .WithMany()
                        .HasForeignKey("PrescribingDoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecord");

                    b.Navigation("PrescribingDoctor");
                });

            modelBuilder.Entity("Hospital.Business.Models.Medical.MedicalRecord", b =>
                {
                    b.HasOne("Hospital.Business.Models.People.Patient", "Patient")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("Hospital.Business.Models.Medical.MedicalRecord", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hospital.Business.Models.People.Patient", b =>
                {
                    b.HasOne("Hospital.Business.Models.Department", "Department")
                        .WithMany("Patients")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hospital.Business.Models.People.Doctor", "AssignedDoctor")
                        .WithMany("Patients")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedDoctor");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Hospital.Business.Models.People.Doctor", b =>
                {
                    b.HasOne("Hospital.Business.Models.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Hospital.Business.Models.People.Nurse", b =>
                {
                    b.HasOne("Hospital.Business.Models.Department", "Department")
                        .WithMany("Nurses")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Hospital.Business.Models.Department", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("Nurses");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("Hospital.Business.Models.Medical.MedicalRecord", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Hospital.Business.Models.People.Patient", b =>
                {
                    b.Navigation("MedicalRecord")
                        .IsRequired();
                });

            modelBuilder.Entity("Hospital.Business.Models.People.Doctor", b =>
                {
                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
